apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-frontend
  namespace: openshift-gitops
  annotations:
    openshift-gitops.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/manifests/pricelist-frontend
    repoURL: https://github.com/sixpac009-teksystems/gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    kind: Route
    jsonPointers:
    - /status/ingress/conditions
