apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: pricelist
  annotations:
    openshift-gitops.argoproj.io/sync-wave: "0"
  labels: argocd.argoproj.io/managed-by: openshift-gitops
spec: {}
status: {}
