apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: pricelist/app-manifest
    repoURL: https://github.com/sixpa009-teksystems/gitops-examples
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true