apiVersion: v1
kind: ResourceQuota
metadata:
  name: pricelist-quota
  namespace: pricelist
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    pods: '10'
    requests.cpu: '2'
    requests.memory: 2Gi
    limits.cpu: '4'
    limits.memory: 4Gi
